name: Build & Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      
      - name: Check if package.json version has been updated
        id: check
        uses: EndBug/version-check@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.2
        if: steps.check.outputs.changed == 'true'
        
      - name: Get npm package version
        id: package-version
        uses: Saionaro/extract-package-version@v1.1.1
        if: steps.check.outputs.changed == 'true'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.version}}
          release_name: v${{ steps.package-version.outputs.version}}
          draft: false
          prerelease: false
        if: steps.check.outputs.changed == 'true'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: steps.check.outputs.changed == 'true'
